token:
  expiration_time: 864000000 
  secret: '{cipher}AYAAPM6uYHvK6TTu1SGDm+eRX31NRSc7TI9XWvL0PczGfUZCQKJeKGIBSfygNFfHZzF6CS68g6pbK2OD/6TUIgi9EIY3BrX+bS4TmcP8PT75HY3xII9QR9TECKV2doMaLbCa5IWGdiMddum9KhFk2etEqg/snt9SJOdNhDyAdHN97rvOU4u+DAcZ+raSyApxgwZ5OkBvNdFdfrlrkSRbxpBY9Y1roaVoi+yvx68urcJo8Qv/0kyGrKxVP3/Vb17lDNoC0Es3ZtBFgbmbqViXXlD83qLTVTKdegPgWHg1NRsi6l1I1REFNTnOEkO+mwF37iTKxNpWCTkHII3lHbW3fn3LXw2RO3WA64VmFmiBNK/eo/hUarZl1ZUd+V0CuLcp7ds8/UIUCvTUXHiFF/U+fBt53XNZpPuADquj37LWPrClenz03vwF36+kdxqIoAF+fknxBU7M+Nb5Z3KjcWOJZwFfR7F7Yr3U5S2TMJ8ajdAaEFjckO4EB4ZPEUc6Sogorb5wB1N73JTbrrAf1XpnHTwFWmWSX+1YJkVm9KMn8uEf0tOvbUkEZNStjo82yItsysXQEwOrWX1va5J3OXyhXWn+4jA/h7r6lTzvar7a9lq+DGs7HavuI/tuxy+Q20lf36Y='

gateway:
  ip: 172.18.0.1
